sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dornick/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true dornick/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-west-2-311974803617"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

